/* Warning: this file is autogenerated by cbindgen. Do not edit manually. */
#ifndef KRONROE_H
#define KRONROE_H
#pragma once

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct KronroeGraphHandle KronroeGraphHandle;

/**
 * Create an in-memory Kronroe database (no file I/O).
 * Ideal for simulator testing and ephemeral workloads.
 * Returns NULL on error (inspect `kronroe_last_error_message`).
 */
KronroeGraphHandle *kronroe_graph_open_in_memory(void);

/**
 * Open/create a Kronroe database and return an opaque handle.
 * Returns NULL on error (inspect `kronroe_last_error_message`).
 */
KronroeGraphHandle *kronroe_graph_open(const char *path);

/**
 * Close and free a graph handle.
 */
void kronroe_graph_close(KronroeGraphHandle *handle);

/**
 * Assert a text fact at current time.
 * Returns false on error.
 */
bool kronroe_graph_assert_text(KronroeGraphHandle *handle,
                               const char *subject,
                               const char *predicate,
                               const char *object);

/**
 * Return all facts about an entity as JSON string.
 * Caller owns the returned string and must free it with `kronroe_string_free`.
 */
char *kronroe_graph_facts_about_json(KronroeGraphHandle *handle, const char *entity);

/**
 * Return last error message for the current thread, or NULL if none.
 * Caller owns the returned string and must free it with `kronroe_string_free`.
 */
const char *kronroe_last_error_message(void);

/**
 * Free strings returned from Kronroe FFI.
 */
void kronroe_string_free(char *ptr);

#ifdef __cplusplus
}
#endif

#endif /* KRONROE_H */
